### ISSUE TITLE
N3Parser ignores extra BLANK_NODE_LABEL or iri when parsing predicateObjectList

### ISSUE THREAD

**Issue by ericprud** [RubenVerborgh/N3.js#100]
While working on the [ShEx Primer](http://shex.io/primer/#simple-expressions-example-1), I used a `,` where I intended a `;`. N3Parser accepted the erroneous graph:

```
PREFIX ex: <http://ex.example/#>
ex:Bob ex:age 14 ,
  ex:hasGuardian ex:Person4 .
```
and got:
```
<http://ex.example/#Bob> <http://ex.example/#age> <http://ex.example/#hasGuardian> .
<http://ex.example/#Bob> <http://ex.example/#age> "14"^^<http://www.w3.org/2001/XMLSchema#integer> .
```
, eliding `ex:Person4`.

To trigger this bug, `14` can be whatever, `ex:Person4` has to be a PrefixedName, IRIREF or BLANK_NODE_LABEL.

**Comment by ericprud** [comment]
Oooo, number 100. Where's my prize?

**Comment by RubenVerborgh** [comment]
N3Parser by default parses a superset of N-Quads and TriG. So the following document would be parsed:
```
<a> <b> <c> <d>.
<g> {
   <x> <y> <z>.
}
```

To constrain the parser to a specific subset, you can do `parser = N3.Parser({ format: 'turtle' })` (or `text/turtle` and other variants). This will then be a fully spec-compatible parser.

The case you've found is actually interpreted as:
```
ex:Bob ex:age ex:hasGuardian.
ex:Person4 { ex:Bob ex:age 14. }
```
So I if you log the `.graph` of the second triple as well, you will see `ex:Person4`.

This finally made me understand why they have chosen to make TriG not a superset of N-Quads.

I'm not sure whether I should actually fix the parser, given that it simply parses a different language/superset that can be restricted to the spec. Moreover, fixing this would require some code that slows down all regular cases (storing whether this current line encountered a semi-colon or comma).

**Comment by ericprud** [comment]
Confirmed. This all makes sense.
So I should really be more diligent about initializing Turtle parsers with `{ format: 'text/turtle' }`. If only the name of the parser could remind me of that, like if it were called "N3Parser"...
