### ISSUE TITLE
Representing infinity

### ISSUE THREAD

**Issue by pietercolpaert** [RubenVerborgh/N3.js#101]
In the tests you test being able to use infinity as follows:
```javascript
      N3Util.createLiteral(Infinity).should.equal('"Infinity"');

```
Src: https://github.com/RubenVerborgh/N3.js/blob/master/test/N3Util-test.js#L381

However, I’d expect this, in RDF to be automatically encoded as follows:
```turtle
"INF"^^xsd:float
# OR
"INF"^^xsd:double
```

What’s the reasoning for using `"Infinity"`?

**Comment by RubenVerborgh** [comment]
Because I didn't know about / check for anything else. You are correct, this should be `INF`, `-INF`, `NaN`, and even `-0`.
