### ISSUE TITLE
someByIRI minor optimisation (?)

### ISSUE THREAD

**Issue by jimsmart** [RubenVerborgh/N3.js#103]
Hi, great work on the latest release!

I was just reading the new code and spotted the following repeated pattern in someByIRI:

```
if (this._findInIndex([...snip...]))
              return true;

[...repeated for each variation, then eventually...]

return false;
```

Because the exit code is simply return false, and there's nothing else happening if the truthy value is returned by _findInIndex, these could all be replaced with:
```
return this._findInIndex([...])
```

Which might be faster (though JIT probably fixes this anyhow), and also makes the code a little easier to read (reducing cyclomatic complexity by a small fraction). 

This particular nit is something that Go 'vet' tool picks up (I always seem to be doing it), don't know if it's something that any of the JS linters can also look for?

Not particularly important, but thought as I'd spotted it I thought I'd mention it.

Cheers

**Comment by RubenVerborgh** [comment]
Looks like it, but actually not true: the `if` statements are wrapped in a `for (var graphId in graphs)` loop, and they can be triggered repeatedly. Only if they result in `true`, the function should return. When they return `false`, the loop should continue.

**Comment by jimsmart** [comment]
My bad. Apologies for the noise

**Comment by RubenVerborgh** [comment]
No worries, don't hesitate if you spot more opportunities :-)
