### ISSUE TITLE
Improve information in error object

### ISSUE THREAD

**Issue by LaurensRietveld** [RubenVerborgh/N3.js#109]
Did you consider adding more information or context to an error object?
E.g. add the token information (as json), as property to the error. This way we don't have to parse the error msg string and extract this information ourselves.

A bonus (though this is probably more suited as another issue) is to add the context (e.g. the 100 chars before, and 100 chars after) to a particular error

**Comment by RubenVerborgh** [comment]
> Did you consider adding more information or context to an error object?

I should!

> E.g. add the token information (as json), as property to the error. This way we don't have to parse the error msg string and extract this information ourselves.

+1, simple fix, big gain

> A bonus (though this is probably more suited as another issue) is to add the context (e.g. the 100 chars before, and 100 chars after) to a particular error

After certainly not a problem; before more tricky. Related to #102.

**Comment by LaurensRietveld** [comment]
I'll submit a PR that adds the line and (if available) as props to the error object. 
Just 2 questions:
- I'll just naively add the props to the err object (i.e., I won't be subclassing and stuff, seems overkill)
- Did you think about using prettier instead of the linter? (finding the linter annoying tbh ;)). Downside will be that most of the line will be marked as modified, i.e. you'll lose history for blaming and stuff

**Comment by RubenVerborgh** [comment]
> I'll submit a PR that adds the line and (if available) token as props to the error object.

Great, added minor comments.

> I'll just naively add the props to the err object (i.e., I won't be subclassing and stuff, seems overkill)

Yes please :-)

> Did you think about using prettier instead of the linter? (finding the linter annoying tbh ;)).

What you call the “annoying” linter is actually [my highly personalized linter configuration](https://github.com/RubenVerborgh/N3.js/blob/master/.eslintrc), which matches the style I want to write 😄 

But I'm open to feedback if there are particular annoyances.

**Comment by LaurensRietveld** [comment]
hehe, nothing in particular about the style that's annoying. Just like the tooling to fix all the errors for me instead

**Comment by RubenVerborgh** [comment]
Following up in #110.
