### ISSUE TITLE
Prettier icw linter

### ISSUE THREAD

**Issue by LaurensRietveld** [RubenVerborgh/N3.js#111]
Couldn't resist, after our short exchange on the linter config in #109.
Did you consider using the linter in combination with prettier? Prettier would take care of the syntax, where linter would take care of all the non-syntactic rules. 
It would make PRs easier, without syntactic / stylistic conformance. (last PR I spend quite some mundane labour fixing syntactic issues)

Take the N3Util file for example (see [repl](https://prettier.io/#%7B%22content%22%3A%22%2F%2F%20**N3Util**%20provides%20N3%20utility%20functions.%5Cn%5Cnvar%20Xsd%20%3D%20'http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23'%3B%5Cnvar%20XsdString%20%20%3D%20Xsd%20%2B%20'string'%3B%5Cnvar%20XsdInteger%20%3D%20Xsd%20%2B%20'integer'%3B%5Cnvar%20XsdDouble%20%3D%20Xsd%20%2B%20'double'%3B%5Cnvar%20XsdBoolean%20%3D%20Xsd%20%2B%20'boolean'%3B%5Cnvar%20RdfLangString%20%3D%20'http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23langString'%3B%5Cn%5Cnvar%20N3Util%20%3D%20%7B%5Cn%20%20%2F%2F%20Tests%20whether%20the%20given%20entity%20(triple%20object)%20represents%20an%20IRI%20in%20the%20N3%20library%5Cn%20%20isIRI%3A%20function%20(entity)%20%7B%5Cn%20%20%20%20if%20(typeof%20entity%20!%3D%3D%20'string')%5Cn%20%20%20%20%20%20return%20false%3B%5Cn%20%20%20%20else%20if%20(entity.length%20%3D%3D%3D%200)%5Cn%20%20%20%20%20%20return%20true%3B%5Cn%20%20%20%20else%20%7B%5Cn%20%20%20%20%20%20var%20firstChar%20%3D%20entity%5B0%5D%3B%5Cn%20%20%20%20%20%20return%20firstChar%20!%3D%3D%20'%5C%22'%20%26%26%20firstChar%20!%3D%3D%20'_'%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%2C%5Cn%5Cn%20%20%2F%2F%20Tests%20whether%20the%20given%20entity%20(triple%20object)%20represents%20a%20literal%20in%20the%20N3%20library%5Cn%20%20isLiteral%3A%20function%20(entity)%20%7B%5Cn%20%20%20%20return%20typeof%20entity%20%3D%3D%3D%20'string'%20%26%26%20entity%5B0%5D%20%3D%3D%3D%20'%5C%22'%3B%5Cn%20%20%7D%2C%5Cn%5Cn%20%20%2F%2F%20Tests%20whether%20the%20given%20entity%20(triple%20object)%20represents%20a%20blank%20node%20in%20the%20N3%20library%5Cn%20%20isBlank%3A%20function%20(entity)%20%7B%5Cn%20%20%20%20return%20typeof%20entity%20%3D%3D%3D%20'string'%20%26%26%20entity.substr(0%2C%202)%20%3D%3D%3D%20'_%3A'%3B%5Cn%20%20%7D%2C%5Cn%5Cn%20%20%2F%2F%20Tests%20whether%20the%20given%20entity%20represents%20the%20default%20graph%5Cn%20%20isDefaultGraph%3A%20function%20(entity)%20%7B%5Cn%20%20%20%20return%20!entity%3B%5Cn%20%20%7D%2C%5Cn%5Cn%20%20%2F%2F%20Tests%20whether%20the%20given%20triple%20is%20in%20the%20default%20graph%5Cn%20%20inDefaultGraph%3A%20function%20(triple)%20%7B%5Cn%20%20%20%20return%20!triple.graph%3B%5Cn%20%20%7D%2C%5Cn%5Cn%20%20%2F%2F%20Gets%20the%20string%20value%20of%20a%20literal%20in%20the%20N3%20library%5Cn%20%20getLiteralValue%3A%20function%20(literal)%20%7B%5Cn%20%20%20%20var%20match%20%3D%20%2F%5E%5C%22(%5B%5E%5D*)%5C%22%2F.exec(literal)%3B%5Cn%20%20%20%20if%20(!match)%5Cn%20%20%20%20%20%20throw%20new%20Error(literal%20%2B%20'%20is%20not%20a%20literal')%3B%5Cn%20%20%20%20return%20match%5B1%5D%3B%5Cn%20%20%7D%2C%5Cn%5Cn%20%20%2F%2F%20Gets%20the%20type%20of%20a%20literal%20in%20the%20N3%20library%5Cn%20%20getLiteralType%3A%20function%20(literal)%20%7B%5Cn%20%20%20%20var%20match%20%3D%20%2F%5E%5C%22%5B%5E%5D*%5C%22(%3F%3A%5C%5C%5E%5C%5C%5E(%5B%5E%5C%22%5D%2B)%7C(%40)%5B%5E%40%5C%22%5D%2B)%3F%24%2F.exec(literal)%3B%5Cn%20%20%20%20if%20(!match)%5Cn%20%20%20%20%20%20throw%20new%20Error(literal%20%2B%20'%20is%20not%20a%20literal')%3B%5Cn%20%20%20%20return%20match%5B1%5D%20%7C%7C%20(match%5B2%5D%20%3F%20RdfLangString%20%3A%20XsdString)%3B%5Cn%20%20%7D%2C%5Cn%5Cn%20%20%2F%2F%20Gets%20the%20language%20of%20a%20literal%20in%20the%20N3%20library%5Cn%20%20getLiteralLanguage%3A%20function%20(literal)%20%7B%5Cn%20%20%20%20var%20match%20%3D%20%2F%5E%5C%22%5B%5E%5D*%5C%22(%3F%3A%40(%5B%5E%40%5C%22%5D%2B)%7C%5C%5C%5E%5C%5C%5E%5B%5E%5C%22%5D%2B)%3F%24%2F.exec(literal)%3B%5Cn%20%20%20%20if%20(!match)%5Cn%20%20%20%20%20%20throw%20new%20Error(literal%20%2B%20'%20is%20not%20a%20literal')%3B%5Cn%20%20%20%20return%20match%5B1%5D%20%3F%20match%5B1%5D.toLowerCase()%20%3A%20''%3B%5Cn%20%20%7D%2C%5Cn%5Cn%20%20%2F%2F%20Tests%20whether%20the%20given%20entity%20(triple%20object)%20represents%20a%20prefixed%20name%5Cn%20%20isPrefixedName%3A%20function%20(entity)%20%7B%5Cn%20%20%20%20return%20typeof%20entity%20%3D%3D%3D%20'string'%20%26%26%20%2F%5E%5B%5E%3A%5C%5C%2F%5C%22'%5D*%3A%5B%5E%3A%5C%5C%2F%5C%22'%5D%2B%24%2F.test(entity)%3B%5Cn%20%20%7D%2C%5Cn%5Cn%20%20%2F%2F%20Expands%20the%20prefixed%20name%20to%20a%20full%20IRI%20(also%20when%20it%20occurs%20as%20a%20literal's%20type)%5Cn%20%20expandPrefixedName%3A%20function%20(prefixedName%2C%20prefixes)%20%7B%5Cn%20%20%20%20var%20match%20%3D%20%2F(%3F%3A%5E%7C%5C%22%5C%5C%5E%5C%5C%5E)(%5B%5E%3A%5C%5C%2F%23%5C%22'%5C%5C%5E_%5D*)%3A%5B%5E%5C%5C%2F%5D*%24%2F.exec(prefixedName)%2C%20prefix%2C%20base%2C%20index%3B%5Cn%20%20%20%20if%20(match)%5Cn%20%20%20%20%20%20prefix%20%3D%20match%5B1%5D%2C%20base%20%3D%20prefixes%5Bprefix%5D%2C%20index%20%3D%20match.index%3B%5Cn%20%20%20%20if%20(base%20%3D%3D%3D%20undefined)%5Cn%20%20%20%20%20%20return%20prefixedName%3B%5Cn%5Cn%20%20%20%20%2F%2F%20The%20match%20index%20is%20non-zero%20when%20expanding%20a%20literal's%20type%5Cn%20%20%20%20return%20index%20%3D%3D%3D%200%20%3F%20base%20%2B%20prefixedName.substr(prefix.length%20%2B%201)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3A%20prefixedName.substr(0%2C%20index%20%2B%203)%20%2B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20base%20%2B%20prefixedName.substr(index%20%2B%20prefix.length%20%2B%204)%3B%5Cn%20%20%7D%2C%5Cn%5Cn%20%20%2F%2F%20Creates%20an%20IRI%20in%20N3.js%20representation%5Cn%20%20createIRI%3A%20function%20(iri)%20%7B%5Cn%20%20%20%20return%20iri%20%26%26%20iri%5B0%5D%20%3D%3D%3D%20'%5C%22'%20%3F%20N3Util.getLiteralValue(iri)%20%3A%20iri%3B%5Cn%20%20%7D%2C%5Cn%5Cn%20%20%2F%2F%20Creates%20a%20literal%20in%20N3.js%20representation%5Cn%20%20createLiteral%3A%20function%20(value%2C%20modifier)%20%7B%5Cn%20%20%20%20if%20(!modifier)%20%7B%5Cn%20%20%20%20%20%20switch%20(typeof%20value)%20%7B%5Cn%20%20%20%20%20%20case%20'boolean'%3A%5Cn%20%20%20%20%20%20%20%20modifier%20%3D%20XsdBoolean%3B%5Cn%20%20%20%20%20%20%20%20break%3B%5Cn%20%20%20%20%20%20case%20'number'%3A%5Cn%20%20%20%20%20%20%20%20if%20(isFinite(value))%5Cn%20%20%20%20%20%20%20%20%20%20modifier%20%3D%20value%20%25%201%20%3D%3D%3D%200%20%3F%20XsdInteger%20%3A%20XsdDouble%3B%5Cn%20%20%20%20%20%20%20%20else%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20modifier%20%3D%20XsdDouble%3B%5Cn%20%20%20%20%20%20%20%20%20%20if%20(!isNaN(value))%5Cn%20%20%20%20%20%20%20%20%20%20%20%20value%20%3D%20value%20%3E%200%20%3F%20'INF'%20%3A%20'-INF'%3B%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20break%3B%5Cn%20%20%20%20%20%20default%3A%5Cn%20%20%20%20%20%20%20%20return%20'%5C%22'%20%2B%20value%20%2B%20'%5C%22'%3B%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%20%20return%20'%5C%22'%20%2B%20value%20%2B%5Cn%20%20%20%20%20%20%20%20%20%20%20(%2F%5E%5Ba-z%5D%2B(-%5Ba-z0-9%5D%2B)*%24%2Fi.test(modifier)%20%3F%20'%5C%22%40'%20%20%2B%20modifier.toLowerCase()%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3A%20'%5C%22%5E%5E'%20%2B%20modifier)%3B%5Cn%20%20%7D%2C%5Cn%5Cn%20%20%2F%2F%20Creates%20a%20function%20that%20prepends%20the%20given%20IRI%20to%20a%20local%20name%5Cn%20%20prefix%3A%20function%20(iri)%20%7B%5Cn%20%20%20%20return%20N3Util.prefixes(%7B%20''%3A%20iri%20%7D)('')%3B%5Cn%20%20%7D%2C%5Cn%5Cn%20%20%2F%2F%20Creates%20a%20function%20that%20allows%20registering%20and%20expanding%20prefixes%5Cn%20%20prefixes%3A%20function%20(defaultPrefixes)%20%7B%5Cn%20%20%20%20%2F%2F%20Add%20all%20of%20the%20default%20prefixes%5Cn%20%20%20%20var%20prefixes%20%3D%20Object.create(null)%3B%5Cn%20%20%20%20for%20(var%20prefix%20in%20defaultPrefixes)%5Cn%20%20%20%20%20%20processPrefix(prefix%2C%20defaultPrefixes%5Bprefix%5D)%3B%5Cn%5Cn%20%20%20%20%2F%2F%20Registers%20a%20new%20prefix%20(if%20an%20IRI%20was%20specified)%5Cn%20%20%20%20%2F%2F%20or%20retrieves%20a%20function%20that%20expands%20an%20existing%20prefix%20(if%20no%20IRI%20was%20specified)%5Cn%20%20%20%20function%20processPrefix(prefix%2C%20iri)%20%7B%5Cn%20%20%20%20%20%20%2F%2F%20Create%20a%20new%20prefix%20if%20an%20IRI%20is%20specified%20or%20the%20prefix%20doesn't%20exist%5Cn%20%20%20%20%20%20if%20(iri%20%7C%7C%20!(prefix%20in%20prefixes))%20%7B%5Cn%20%20%20%20%20%20%20%20var%20cache%20%3D%20Object.create(null)%3B%5Cn%20%20%20%20%20%20%20%20iri%20%3D%20iri%20%7C%7C%20''%3B%5Cn%20%20%20%20%20%20%20%20%2F%2F%20Create%20a%20function%20that%20expands%20the%20prefix%5Cn%20%20%20%20%20%20%20%20prefixes%5Bprefix%5D%20%3D%20function%20(localName)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20return%20cache%5BlocalName%5D%20%7C%7C%20(cache%5BlocalName%5D%20%3D%20iri%20%2B%20localName)%3B%5Cn%20%20%20%20%20%20%20%20%7D%3B%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20return%20prefixes%5Bprefix%5D%3B%5Cn%20%20%20%20%7D%5Cn%20%20%20%20return%20processPrefix%3B%5Cn%20%20%7D%2C%5Cn%7D%3B%5Cn%5Cn%2F%2F%20%23%23%20Exports%5Cnmodule.exports%20%3D%20N3Util%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)). If I applied prettier using this cmd [1], you'd be left with these linting errors:

- space-before-function-paren
- indent
- operator-linebreak

If you could live with that, that'd be great ;)

[1] `prettier --single-quote ---trailing-comma all`

**Comment by RubenVerborgh** [comment]
Thanks for trying this out!

Hmmm, this `prettier` config makes some choices that affect readability, but there might be other configs that achieve something that makes me happy. I will check!

**Comment by RubenVerborgh** [comment]
I noticed that `eslint` has a [`--fix` option](http://eslint.org/docs/user-guide/command-line-interface#--fix). Would that have achieved the same?

**Comment by LaurensRietveld** [comment]
It would to some degree. But afaik, with lint you'll be able to write your code in a number of ways while still adhering to the linting rules. 
Prettier always serializes to one and the same syntax, as it first generates an AST, and serializes from that. 

You could however use both prettier and eslint with the `--fix` option (see https://github.com/prettier/prettier-eslint). Such a setup might even pass the rules you currently have.

**Comment by RubenVerborgh** [comment]
> Prettier always serializes to one and the same syntax

Didn't realize that.

I'll have to think about this for a bit. Currently, I'm a bit concerned about the Prettier output (especially the manual layout that I put in there, which ESLint will not fix). Might be difficult for this particular project (given the syntactical complexity of a parser), but meaningful for other projects where I currently use ESLint.

**Comment by LaurensRietveld** [comment]
As a reference, I applied prettier-eslint to the lib folder, see: https://github.com/OpenTriply/N3.js/tree/prettier
It passes all the linting rules.

You're point about the syntactic complexity of a parser is a valid one though. One workaround exists in prettier to skip the next node in the AST from being prettified (using `// prettier-ignore`), but that's something that you'd want to avoid doing too often. 

Another downside btw will be that you'll mess up the git history: it'll be difficult doing a `git blame` when the whole repo is reformatted.

**Comment by RubenVerborgh** [comment]
Good to hear it works. Some [shady stuff](https://github.com/OpenTriply/N3.js/commit/427d4d3664794c20d5125633a1044d5c6f5180f7#diff-afb851a45844860757facedbac6cef07R197) there though (but admittedly, that's due to my use of the comma operator).

**Comment by RubenVerborgh** [comment]
I was recently confronted with some of the absurdity of (too much) prettier: https://github.com/babel/babel/pull/6219/files#diff-56f320a6a89e1ca4a32a0cbb2da293a1R76

Those 4 assertions are highly similar, and should look the same so we can compare them easily. However, the way I committed the code was the only way the linter would accept it.

**Comment by LaurensRietveld** [comment]
Haha, nice example of a shortcoming. But on the bright side: you didn't have to adjust your style to someone else's linting config ;)

**Comment by RubenVerborgh** [comment]
Not taking this up right now, but might still consider for a future release.
