### ISSUE TITLE
Carriage returns in string literals

### ISSUE THREAD

**Issue by inukshuk** [RubenVerborgh/N3.js#115]
First off, thanks for the N3 parser and API!

I've run into a problem parsing [a vocabulary](http://lov.okfn.org/dataset/lov/vocabs/cwrc) because a string literal contains a carriage return. I think the carriage return in question is erroneous, but since this vocabulary comes from LOV I'm wondering if the parser should actually accept this?

For reference, the carriage return is at the end of line 3569 of the vocabulary linked above. The error thrown is:

```
Error: Unexpected ""泛稱源自宗教改革的各式基督信仰。雖然早期的新教形
式是指遵循路德(Luther)、喀爾文(Calvin)，以及茨溫利(Zwingli)的派別，但現在新教這
個詞彙包含了大部分非羅馬天主教或非正教的派別。新教徒希望能更接近早期教會信仰， $
為天主教將之變得晦澀難解。本詞彙衍生自”protestari”，不僅意指抗議，更要坦白或懺 $
。新教的常見特色包括因純信而稱義、經典的權威性、信徒皆牧師，所以不是只有牧師才 $
聽取認罪懺悔。" on line 3569.
    at N3Lexer._syntaxError (/Users/dupin/Work/tropy/tropy/node_modules/n3/lib/$
3Lexer.js:364:15)
    at reportSyntaxError (/Users/dupin/Work/tropy/tropy/node_modules/n3/lib/N3Le
xer.js:331:54)
    at N3Lexer._tokenizeToEnd (/Users/dupin/Work/tropy/tropy/node_modules/n3/lib
/N3Lexer.js:316:18)``

**Comment by RubenVerborgh** [comment]
Hi @inukshuk, [carriage returns re indeed not allowed in single-quoted literals](https://www.w3.org/TR/turtle/#grammar-production-STRING_LITERAL_QUOTE).

Therefore, the file is invalid and N3.js must reject it.

**Comment by inukshuk** [comment]
Thanks, that's great to know! I'll see if I can report this to LOV then.
