### ISSUE TITLE
Buggy occurrence of semicolon is parsed

### ISSUE THREAD

**Issue by wouterbeek** [RubenVerborgh/N3.js#116]
The following buggy Turtle snippet is parsed by N3:

```ttl
<x:y> ; <x:y> <x:y> .
```

N3 parses a triple, but incorrectly so; the semicolon should have given an error.

Tested on N3 0.11.1.

**Comment by RubenVerborgh** [comment]
Ooh, that's nasty. Also, where do you guys keep on getting all those dirty Turtle files? (Never mind, I know!)

**Comment by RubenVerborgh** [comment]
Thanks for reporting! Fixed and released as v0.11.2.
