### ISSUE TITLE
Question: is there anyway to write sparql query?

### ISSUE THREAD

**Issue by jameel-samaan** [RubenVerborgh/N3.js#117]
Hi,
I like the way this api works and espacially that it is the only JS library that parses N-Quads. I was wondering if there is any way to consume native sparql queries to interact with the store instead of using funtions like addTriples and getTriples?

Thanks in advance!

Jameel

**Comment by RubenVerborgh** [comment]
Hi Jameel,

N3.js currently does not implement a SPARQL query processor. Preliminary work for read queries is available here: https://github.com/LinkedDataFragments/Client.js/

Best,

Ruben

**Comment by jameel-samaan** [comment]
Hi Ruben,
Thank you for your answer.

I will try to apply the Client.js in my code. I think it will work properly. But I will let you know about the results ;)

Is there any plan to let N3.js able to accept pure SPARQL query in the future? Or is your preference to let Client.js do the job of querying?

Regards,
Jameel

**Comment by RubenVerborgh** [comment]
No plans for N3.js to accept SPARQL, but there are plans to create a separate SPARQL engine (that works together with N3.js).

**Comment by jameel-samaan** [comment]
That is great 🥇
Thanks 💯 for N3.js and for your support!

**Comment by eddie-thomas** [comment]
@RubenVerborgh Is the [query spec](https://rdf.js.org/query-spec/) meant to be the SPARQL engine you reference below? If so, I cannot find documentation to code examples. Any help would be appreciated!

> No plans for N3.js to accept SPARQL, but there are plans to create a separate SPARQL engine (that works together with N3.js).

**Comment by jacoscaz** [comment]
@eddie-thomas there's likely other packages that are better suited for the task but, for the time being, you should be able to use [quadstore-comunica](https://www.npmjs.com/package/quadstore-comunica). I just tested with the following:

```typescript
import n3 from 'n3';
import { Engine } from 'quadstore-comunica';
import { ArrayIterator } from 'asynciterator';
import { DataFactory } from 'rdf-data-factory';

(async () => {

  const df = new DataFactory();
  const store = new n3.Store();
  const engine = new Engine(store as any);
  
  store.import(new ArrayIterator([
    df.quad(
      df.namedNode('ex://sub'),
      df.namedNode('ex://prd'),
      df.namedNode('ex://obj'),
    )
  ]));
  
  const readable = await engine.queryBindings('SELECT * WHERE {?s ?p ?o}');

  readable.on('data', (bindings) => {
    console.log('BINDINGS', bindings.entries.toJSON());
  });

})().catch(console.error);
```

Bear in mind that it's built for use with [quadstore](https://www.npmjs.com/package/quadstore) so it assumes the following dependencies to be already installed: `sparqljs`, `sparqlalgebrajs` and `asynciterator`. However, it does not yet implement quadstore-specific query operators, so ATM it's usable with any implementation of  the RDF/JS `Source`/`Sink`/`Store` interfaces such as N3's `Store`. YMMV

**Comment by eddie-thomas** [comment]
@jacoscaz That's awesome, thank you for the example and a great jump off point!

**Comment by jeswr** [comment]
Comunica works with it (https://github.com/comunica/comunica/) out of the box of you provide the N3store as a source (i.e. one does not need to load it into quadstore first)

**Comment by jacoscaz** [comment]
@jeswr is right!  Eventually @eddie-thomas you should move to use Comunica directly if you find that quadstore-comunica works for you. The latter is just (IMHO, and I am biased) a simpler and more immediate entrypoint to the Comunica ecosystem as it ships pre-built and in bundled form (few dependencies), with support for ES modules and a few other tricks that lower the overall bundle size.

**Comment by eddie-thomas** [comment]
@jacoscaz @jeswr Thank you both for the guidance, I very much appreciate the quick and informative responses.
