### ISSUE TITLE
N3Writer no whitespace before dot

### ISSUE THREAD

**Issue by melgish** [RubenVerborgh/N3.js#119]
I hesitate to call this a bug, as it's more of a suggestion.

Comparing N-Triple output of N3 with output of https://dbpedia.org/sparql. I see that the later includes a space before the dot on each line while N3 does not. 

I realize the spec doesn't explicitly require it, but I feel having it there will make output more compatible with other implementations.  (I'm having difficulty uploading N3 output into Apache Jena due to the format difference)

From what I can tell this is a simple change to tripleToString.

Thanks.

**Comment by RubenVerborgh** [comment]
The writer follows the N-Triples specification, which indeed does not require that space. So it seems that Apache Jena has a bug. Did you configure Jena to read N-Triples (not N3)?

It'd be interested to see an example of data that goes wrong (and I suspect the Jena people would be as well).

**Comment by melgish** [comment]
I'm on my way to the Jena project next.  We're using org.apache.jena.riot.RDFDataMgr.read to load the stream.
