### ISSUE TITLE
Natively support DataFactory interface

### ISSUE THREAD

**Issue by nichtich** [RubenVerborgh/N3.js#122]
Having to plug [rdf-ext](https://github.com/rdf-ext/rdf-ext) on top of N3 is overly complex, unless you are part of the RDFJS Representation Task Force. Applications that just want to serialize RDF in a clean way should use the DataFactory interface, but the native N3 interface will likely be preferred because it does not require additional specifications, documentation, and dependencies.

**Comment by RubenVerborgh** [comment]
Agree, this part of the plan. We currently have #118 for RDF/JS compatibility, but this does not yet include `DataFactory`. @rubensworks, what do you think?

**Comment by rubensworks** [comment]
Yep, [I agree](https://github.com/RubenVerborgh/N3.js/pull/118#issuecomment-342013755). I don't have any time to continue work on this in the near future though, I'll look into it somewhere in January.

**Comment by RubenVerborgh** [comment]
@rubensworks You and I should sit together for one or two days in January and get this thing out once and for all :-)

**Comment by RubenVerborgh** [comment]
Implemented in #118.
