### ISSUE TITLE
@prefix : <#> . ?

### ISSUE THREAD

**Issue by infiniteperplexity** [RubenVerborgh/N3.js#124]
Is there a syntax to add this commonly-used prefix to a store?

**Comment by RubenVerborgh** [comment]
`store.addPrefix('', 'http://example.org/foo#')`?

**Comment by infiniteperplexity** [comment]
Thanks!  I should've been able to figure that out myself :/

**Comment by RubenVerborgh** [comment]
Ah well, the documentation could be more extensive :wink:
