### ISSUE TITLE
Store doesn't support adding triples using prefixed IRIs

### ISSUE THREAD

**Issue by marcelreppi** [RubenVerborgh/N3.js#126]
In the documentation it says that the prefixes would support the addition **and** lookup of triples, but when adding a triple with a previously added prefix the prefixed URI is not being expanded and the triple is being store with the prefixed URI. I would have expected the triple to be stored with the expanded absolute URIs.

The lookup with prefixed URIs works fine.

Is this the intended behaviour?

**Comment by RubenVerborgh** [comment]
Hi @marcelreppi 

> In the documentation it says that the prefixes would support the addition and lookup of triples

Where does it say that?

> when adding a triple with a previously added prefix

The [N3.js in-memory representation](https://github.com/RubenVerborgh/N3.js#triple-representation) always uses full IRIs everywhere. So you cannot abbreviate IRIs.

> Is this the intended behaviour?

Yes.

**Comment by marcelreppi** [comment]
Thanks for you quick reply!

I just realized my title wasn't clear enough. I was talking about the N3 Store.

In the documentation for the store it says: "`addPrefix ` to register a prefix (facilitating addition and lookup)"

When I use the `store.addTriple(s, p, o)` method it does not recognize previously stored prefixes

**Comment by RubenVerborgh** [comment]
> I was talking about the N3 Store.

Yes, me too :wink:

> In the documentation for the store it says: "addPrefix to register a prefix (facilitating addition and lookup)"

That's a mistake, fixed this in f4561c91a622d2120b999c17980e81cf9f06ce94.

> When I use the store.addTriple(s, p, o) method it does not recognize previously stored prefixes

Indeed, because the N3.js in-memory model for triples always uses full IRIs.

**Comment by marcelreppi** [comment]
Great! Thanks for the clarification.
