### ISSUE TITLE
Backslash escaped IRI local names are not parsed

### ISSUE THREAD

**Issue by wouterbeek** [RubenVerborgh/N3.js#127]
N3 does not currently parse backslash escaping in IRI local names.  For example, the parser emits an error for the following input:

```ttl
prefix : <x:x>
:\. : : .
```

**Comment by RubenVerborgh** [comment]
Thanks for reporting. Can't believe this went unnoticed for so long, and that the spec tests don't capture this.

**Comment by wouterbeek** [comment]
As Michael Jackson said: [You are not alone](https://github.com/drobilla/serd/issues/13) ;-)

Somebody™ should come up with a more comprehensive test suite some day.

**Comment by RubenVerborgh** [comment]
Aatually, reserved character escape sequences are supported: https://github.com/RubenVerborgh/N3.js/blob/v0.11.2/test/N3Lexer-test.js#L160-L163

So must be a different error.

**Comment by RubenVerborgh** [comment]
Can't reproduce with v0.11.2:
```javascript
new N3.Parser().parse(`
prefix : <x:x>
:\\. :b :c .
`, (e, t) => console.log(t));
// { subject: 'x:x.', predicate: 'x:xb', object: 'x:xc', graph: '' }
// null
```
