### ISSUE TITLE
Add version number inside compiled source files

### ISSUE THREAD

**Issue by l00mi** [RubenVerborgh/N3.js#34]
Please add the version number inside the library files. Can be very  help full for debugging purposes.
Either as simple comment on top of the file. Or also as an property which can be accessed inside the JavaScript context.

**Comment by RubenVerborgh** [comment]
Any suggestion on the best way to do this in a sustainable way?

The thing that worries me most is consistency of course. I could add it to source files, but how do I ensure it is always updated when I publish a new version? (Perhaps I should just add a script.)

**Comment by l00mi** [comment]
I'm not a JavaScript package manager wizard at all. But I guess you keep the package.json up-to-date anyway? For the generated browser sourcefile it might be easiest to fetch the information there and add it inside the header of the file?

**Comment by RubenVerborgh** [comment]
package.json is updated automatically by `npm version`.

I suspect the problem would indeed be the generated browser sourcefile. If `package.json` is a dependency, it would be sent to browsers in its entirety, which is also not good.

I'll think this through and propose something.

**Comment by betehess** [comment]
I am not sure if this is exactly the same issue, but you could tag the `browser` branch with the version number. That would help with https://github.com/webjars/webjars/issues/796#issuecomment-71325178 .

**Comment by RubenVerborgh** [comment]
@betehess I cannot unfortunately, since the version tags are already used in the `main` branch.

**Comment by betehess** [comment]
So maybe a simple directory structure would do it?

**Comment by RubenVerborgh** [comment]
That could indeed be a possibility. I just haven't found a way to please all package managers (while still keeping a healthy git code repository).

**Comment by betehess** [comment]
In the meantime, the WebJar version uses the git sha so it's not a big deal, just a bit confusing.
