### ISSUE TITLE
"constructor" for RDF terms

### ISSUE THREAD

**Issue by betehess** [RubenVerborgh/N3.js#36]
`N3.Util` already provides utility functions to unfold the internal representation for RDF terms.

It would be very useful to have their counterparts, so that we could construct such elements e.g. `makeLiteral("3", "http://www.w3.org/2001/XMLSchema#integer")`, `makeLiteral(3)`, `makeUri("http://example.org/cartoons#Mickey")`, etc.

**Comment by RubenVerborgh** [comment]
Thanks for this suggestion!

**Comment by RubenVerborgh** [comment]
(Note that `makeUri` would be the identity function though; but it would not be bad to have this for consistency.)

**Comment by betehess** [comment]
Another tricky part is the Blank Nodes and their local scope... I am not sure what the correct function should look like.

**Comment by RubenVerborgh** [comment]
Probably just something like `var b = 0; function createBlank() { return '_:bb' + (b++); }`.

**Comment by betehess** [comment]
Ah, true, it's bit easier in a Javascript context as `b` won't be shared among threads :-)

But this doesn't prevent one from using the same bnode in different graphs. This could lead to issues when trying to compute the union of two graphs sharing bnodes with the same internal representation. Or in any scenario where a bnode gets reused among different graphs.

Also, what about `createBlank("myLabel")` then? A nice property is that "myLabel" would be preserved when serializing in let's say Turtle. Would the intermediate representation allow that?

**Comment by RubenVerborgh** [comment]
Agreed: `var b = 0; function createBlank(label) { return (label || '_:bb') + (b++); }`.
Actually, something like this [is currently in `N3Store`](https://github.com/RubenVerborgh/N3.js/blob/v0.4.1/lib/N3Store.js#L340); probably needs to move to `N3Util` indeed.

**Comment by betehess** [comment]
The changeset only covers URI and Literal constructions. Do you want me to open a different issue for that?

**Comment by betehess** [comment]
Ah, I see you have already done that :-)

**Comment by RubenVerborgh** [comment]
:wink:
