### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by D063520** [RubenVerborgh/N3.js#38]
Hi Ruben, 

thank you for your great Parser! I'm parsing a big file and writing the output to a file. It is really fast and I would like to parse even faster by executing it in parallel. My idea was the following:

1) assuming the machine has N-cores, split the file to parse into n parts, say file1, file2, file3, ..., fileN ;

2) add to file2 all lines of file1 beginning with @ ,
    add to file3 all lines of file1 and file1 beginning with @,
   and so on .... (this way prefixes will not be lost)

3) launch N-times the parser using N child processing on files1, ..., fileN respectively. 

Then I would be able to parse N-time faster. Now my problem. How can I split the files instep 1) such that data that belongs to one turtle entry is not split up. Do you have an idea? Do you see some other problems using this strategy?

Thank you
Dennis

**Comment by RubenVerborgh** [comment]
Hi Dennis,

Thanks!

Unfortunately, what you propose cannot be done in general. After all, a prefix or base declaration `@` does not necessarily appear at the start of a line. Moreover, Turtle allows prefix and base declarations without the `@` sign as well.

And lastly, JavaScript is single-threaded. Even though you might use workers, you would have to share an immense amount of data between them, which is not ideal either.

So I'll not be able to implement this, because there is no possible general strategy to split a Turtle file in different parts. (For N-Triples and N-Quads, the story is different though.)

Best,

Ruben

**Comment by D063520** [comment]
Hi Ruben,

thank you for your fast Answer! I have some questions about it, can I ?

I looked up the Turtle grammar and I saw that the prefixes can be introduced by @prexif, @base, BASE and PREFIX and yes, they have not to be at the beginning of the line. I agree with you that if there are too many of this prefixes then the strategy makes no sense (I find it a bit sad because then I think that without parallelization turtle is not a good format to exchange big files). But assuming there are not to many of them then it should work. Or?

I tried to search with grep a document with 5 million rows like this

 time -p grep --color '@prefix\|@base\|BASE\|prefix' 5M.n3

and it takes 2,3 seconds for 423 matches. To parse the hole file I need 360 seconds! So understanding if it is a real prefix or only something like "prefixions", "prefixal", ... is the same as understanding if two lines where split smoothly or not. Do you have an idea to do that?

Thank you
Dennis

**Comment by RubenVerborgh** [comment]
Turtle has not been designed to parse in parallel, but this doesn't make it a bad format for big files.
Two main problems hinder parallelization.

### Finding prefix/base statements

A case-insensitive search for `/@?prefix|@?base/` can identify them, but will yield false positives. In particular, matches inside strings should be disregarded. This is quite complex, as an example shows:

```
@prefix a: <b>. # a prefix
# "
a:b a:c """.

@prefix a: <b>. # not a prefix
# "
a:b a:c """.
```

### Splitting the file
Assuming you have identified all prefixes correctly, you need to slice the file. This is also non-trivial, as the example below shows.

```
<a> <b> "\"".
# Safe to split here
<a> <b> <c>, """.

<a> <b> "\"".
# Not safe to split here
<a> <b> <c>, """.
```


So if you want parallelization, you need to solve both of these problems. I'm not saying it's impossible, but the software that solves those problems will likely be almost as complex as an actual parser, defeating its purpose.
