### ISSUE TITLE
Add helper method for list creation

### ISSUE THREAD

**Issue by RubenVerborgh** [RubenVerborgh/N3.js#40]
Lists are common structures; in RDF, their represented by `rdf:first`, `rdf:rest`, and `rdf:nil`. It would be handy if there as a helper method to create the relevant triples from a JavaScript array.
This could be implemented in `N3.Util`, but also in `N3.Writer`.

Raised by @iherman.

**Comment by iherman** [comment]
And, to complete this request: it would be also nice if the output of, say, Writer would also use this syntax...

**Comment by RubenVerborgh** [comment]
Absolutely, but due to the streaming nature of N3.js, those would need to be different. In Turtle, lists can only be written in the `(…)` syntax if a) the list is complete b) there are no other triples involving the blank nodes of the list heads. In a stream, a) and b) cannot be guaranteed without keeping those triple in memory until everything has been written.

Currently, I'm thinking:
```JavaScript
N3.Util.toList([1, 2, 3, 4]);
writer.addTriple('s', 'p', writer.createList([1, 2, 3, 4]));
```

**Comment by iherman** [comment]
> On 15 Feb 2015, at 15:44 , Ruben Verborgh <notifications@github.com> wrote:
> 
> Absolutely, but due to the streaming nature of N3.js, those would need to be different. In Turtle, lists can only be written in the (…) syntax if a) the list is complete b) there are no other triples involving the blank nodes of the list heads. In a stream, a) and b) cannot be guaranteed without keeping those triple in memory until everything has been written.
> 
> Currently, I'm thinking:
> 
> N3.Util.toList([1, 2, 3, 4
> ]);
> writer.addTriple(
> 's', 'p', writer.createList([1, 2, 3, 4]));

I am fine with it. It sounds perfectly all right if the user has the responsibility to 'collect' the elements of the list.

Ivan


> —
> Reply to this email directly or view it on GitHub.
> 


----
Ivan Herman
Bankrashof 108
1183NW Amstelveen, The Netherlands
http://www.ivan-herman.net
