### ISSUE TITLE
Add helper method for anonymous blank nodes

### ISSUE THREAD

**Issue by RubenVerborgh** [RubenVerborgh/N3.js#41]
The current writer can only write named blank nodes. Sometimes, the anonymous `[…]` syntax is preferred.

Raised by @iherman.

**Comment by tibotiber** [comment]
Hi @RubenVerborgh and @iherman, would this let us write something like 
```writer.addTriple('s', 'p', '[ p1 o1; p2 o2 ]');``` 
or 
```writer.addTriple('s', 'p', writer.createBlankNode([{predicate: 'p1', object: 'o1'}, {predicate: 'p2', object: 'o2'}]');```
If yes, I'd be really interested. Is there any update on this?

**Comment by RubenVerborgh** [comment]
The second option is actually what I want (because the first introduces new in-memory representations). No update on this yet, but I will prioritize this in my todo list.

**Comment by tibotiber** [comment]
Great! Thank you :).

**Comment by RubenVerborgh** [comment]
Supported syntaxes are:

```JavaScript
writer.addTriple('s1', 'p', writer.blank());
writer.addTriple('s2', 'p', writer.blank('p1', 'p2'));
writer.addTriple('s2', 'p', writer.blank({ predicate: 'p1', object: 'p2'}));
writer.addTriple('s3', 'p', writer.blank([{predicate: 'p1', object: 'o1'}, {predicate: 'p2', object: 'o2'}]));
```

**Comment by tibotiber** [comment]
Great! Thank you.
Is there any way to support this for `store.addTriple()`? On this one, i'm really unsure...

Do give you some context, here is my (simplified) code:
```js
[...]
var bnid = 0;
_.each(states, function(state) {
  /*
  // maybe one day if https://github.com/RubenVerborgh/N3.js/issues/41 is supported for store.addTriple()
  // should replace what's below and the bnid
  var stateDetails = _.map(state, function(value, key) {
    return { predicate: 'qol:'+key, object: '"'+value+'"^^xsd:boolean' };
  });
  store.addTriple('hom:'+sensApp.name, 'qol:hasPossibleState', store.blank(stateDetails));
  */
  bnid++;
  var bn = '_:'+sensApp.name+bnid; // create my unique blank node
  store.addTriple('hom:'+sensApp.name, 'qol:hasPossibleState', bn);
  _.each(state, function(value, key) {
    store.addTriple(bn, 'qol:'+key, '"'+value+'"^^xsd:boolean');
  });
});
[...]
```

**Comment by RubenVerborgh** [comment]
This is purely a cosmetic feature for the writer; it doesn't affect blank node support in any way.

`store.createBlankNode()` could replace `'_:'+sensApp.name+bnid, so that might simplify things.
Creating the “nested” triples is done best in the way you propose though.

**Comment by tibotiber** [comment]
Thanks for the feedback!

I didn't know about `store.createBlankNode()` and it seems perfect for what I need. Maybe it would be good mentioning it in the README?

However, I'm having a new issue when I replace `'_:'+sensApp.name+bnid` by `store.createBlankNode()`. It is very strange. The blank nodes are created as expected `_:b0`, `_:b1`, etc. I have no problem adding triples using them to the store, but after that when I want to dump the store to a stream I get the following error:
```
Error: A literal as subject is not allowed: "14"^^http://www.w3.org/2001/XMLSchema#integer
        at Object.N3Writer._writeSubject (/home/tibo/ubismart/node_modules/n3/lib/N3Writer.js:86:13)
        at Object.N3Writer.addTriple (/home/tibo/ubismart/node_modules/n3/lib/N3Writer.js:140:14)
        at /home/tibo/ubismart/ubi/core/kb/n3store.js:101:10
        at /home/tibo/ubismart/node_modules/async/lib/async.js:187:20
        at iterate (/home/tibo/ubismart/node_modules/async/lib/async.js:265:13)
        at process._tickDomainCallback (node.js:463:13)
```
I have checked and I am sure no `store.addTriple()` is executed with such literal subject. However, when dumping the store, there is one. If I revert `store.createBlankNode()` to my old code, the error disappears. 
Do you have any idea? Do you prefer I post this as an independent issue?

**Comment by RubenVerborgh** [comment]
Very strange, because [`_writeSubject` just checks if the first character of the string is `"`](https://github.com/RubenVerborgh/N3.js/blob/v0.4.4/lib/N3Writer.js#L138), which should most definitely not be the case. Can you create a new issue with a minimal example? Thanks!

**Comment by tibotiber** [comment]
All right!
