### ISSUE TITLE
Writing a large amount of triples seems slow

### ISSUE THREAD

**Issue by shuanzi** [RubenVerborgh/N3.js#45]
Hi, all~
 
When doing `writer.addTriple`, it seems that only one tripple a time. And that would be deadly slow (say 300000 tripples would cost about 10 min) when dealing with large numbers of tripples.

As what i asked, i'm trying to do it like this:

`writer.addTriple({`
`      subject: fullNameUrl,`
`      predicate: 'http://example.org/property/contact#FN',`
`      object: '"' + 'FN' + i + '"'`
`    }, {`
`      subject: fullNameUrl,`
`      predicate: 'http://example.org/property/contact#name',`
`      object: '"' + 'Name' + i + '"'`
`    }, {`
`      subject: fullNameUrl,`
`      predicate: 'http://example.org/property/contact#sex',`
`      object: '"' + 'sex' + '"'`
`    }, {`
`      subject: fullNameUrl,`
`      predicate: 'http://example.org/property/contact#Email',`
`      object: '"' + 'EmailAddr' + '"'`
`    }`
`)`

But somehow, it only works with the first tripple there.
If anyone could give me some advice or clue about it and that would be realy helpful.

Thanks, all~

**Comment by RubenVerborgh** [comment]
That's right: `addTriple` adds a single triple. To add multiple triples, use `addTriples`:
```JavaScript
writer.addTriples([
  {
    subject: fullNameUrl,
    predicate: 'http://example.org/property/contact#FN',
    object: '"' + 'FN' + i + '"'
  },
  {
    subject: fullNameUrl,
    predicate: 'http://example.org/property/contact#name',
    object: '"' + 'Name' + i + '"'
  }
]);
```
Note the extra brackets `[…]`, i.e., `addTriples` accepts an array.

However, internally, [`addTriples` will simply call `addTriple` multiple times](https://github.com/RubenVerborgh/N3.js/blob/v0.4.2/lib/N3Writer.js#L173-L177), so this will not help performance.

If you say "deadly slow", what is your exact setup? I.e., can I see the surrounding code?

**Comment by shuanzi** [comment]
I mentioned that dealing with 30000 triples, it costs about 10 min. And here is my testing code.

```javascript
for (var i = 0; i < 30000; i++) {
	var currentTime = (new Date());
	var fullName = "FullName" + i;
	var fullNameUrl = 'http://example.org/item/contact#' + fullName;

	writer.addTriple(fullNameUrl,
		'http://www.w3.org/1999/02/22-rdf-syntax-ns#type',
		'http://example.org/category#Contact');
	writer.addTriple({
		subject: fullNameUrl,
		predicate: 'http://example.org/property/contact#FN',
		object: '"' + 'FN' + i + '"'
	});

      //...
      //some other properties

}

writer.end();

fileWriteStream.on('error', function(err) {
	callback(err);
})

fileWriteStream.on('finish', function() {
	var endTime = new Date();
	var timeSpan = endTime.getTime() - startTime.getTime();
	callback(null, timeSpan);
});
}
```

**Comment by RubenVerborgh** [comment]
Have you considered buffering the stream to the file? Because I can imagine now that each individual write has to go through the entire stack (JavaScript – Node – file system). Buffering would be able to speed this up.

That said, are you happy with this resolution? If so, we can close the issue.

**Comment by shuanzi** [comment]
Got it! Thanks for your help. And I think we can close this issue now.
