### ISSUE TITLE
C implementation of rdf2hdt fails when reading triples from N3.Writer

### ISSUE THREAD

**Issue by pabloem** [RubenVerborgh/N3.js#49]
This is actually a bug of the C implementation, rather than the N3.Writer; but maybe we can make a small change in the N3.Writer and get rid of the problem.
Basically, rdf2hdt fails whenever the final dot in each triple in N-triples format does not have a space before it.

e.g.: The following line errors out:

    <http://www.w3.org/2001/sw/RDFCore/ntriples/> <http://purl.org/dc/terms/title> "N-Triples"@en-us.

While the following one doesn't:

    <http://www.w3.org/2001/sw/RDFCore/ntriples/> <http://purl.org/dc/terms/title> "N-Triples"@en-us .

Note the whitespace between the object and the finishing `.`.
Would you want to add it? I can make a pull request with it, if you think it's fine.
Best

P.

**Comment by RubenVerborgh** [comment]
N3.Write is spec-compatible; rdf2hdt apparently is not. Therefore, it's really rdf2hdt that should be updated.

Did you convert this with `-f turtle` (which is necessary)? In that case, it's a bug in SERD.

**Comment by pabloem** [comment]
I'm sorry, what do you mean about converting with `-f turtle`?

**Comment by RubenVerborgh** [comment]
The command line you use to execute rdf2hdt should be `rdf2hdt -f turtle in.ttl out.hdt`. Is it?

**Comment by pabloem** [comment]
I was using `ntriples`, not `turtle`. Embarrassment : )
Sorry about the trouple.

**Comment by RubenVerborgh** [comment]
No worries, it is actually valid N-Triples. It's just that the `ntriples` parser of rdf2hdt is seriously broken.
