### ISSUE TITLE
store.createBlankNode() takes name of last resource added to store

### ISSUE THREAD

**Issue by tibotiber** [RubenVerborgh/N3.js#54]
Hi Ruben,
This is a follow up on the report started in #41. I've made a sample code detailing the issue in https://github.com/tibotiber/blank. Hope this helps you. I'm available for any help if needed.
Cheers and thanks.

**Comment by RubenVerborgh** [comment]
Thanks for reporting!
The fix was embarrassingly simple… used `id++` where I should have used `++id`.

**Comment by tibotiber** [comment]
You're welcome and thanks for the fix. Embarrassing as it can be, it worked like a charm :).
If you can let me know when you'll publish the new version to npm so I correct my `package.json`, that'd be great. Thanks again!

**Comment by RubenVerborgh** [comment]
Published as version 0.4.5.

**Comment by tibotiber** [comment]
:+1: Thanks
