### ISSUE TITLE
Add example code for Node.js and browser

### ISSUE THREAD

**Issue by drBenway** [RubenVerborgh/N3.js#59]
Could you please provide some example code. I often find it more easy to grasp code then written documentation.

**Comment by RubenVerborgh** [comment]
Good point indeed. Do things like this help? https://github.com/RubenVerborgh/N3.js#from-an-rdf-document-to-triples

What else would you like to see?

**Comment by RubenVerborgh** [comment]
Closing this for now; can be reopened if more details are provided.
