### ISSUE TITLE
Allow synchronous string parsing

### ISSUE THREAD

**Issue by aindlq** [RubenVerborgh/N3.js#60]
Hi, 

It is not really an issue, but I didn't find better place to ask. I'm going to ask very stupid question, but maybe you have any suggestions :)

Is it possible to parse turtle with N3.js synchronously? I'm trying to use [ES6 taged template strings](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/template_strings#Tagged_template_strings
) for turtle parsing. E.g something like this:
```js
const res = turtle`<http://example.com/A> a <http://example.com/B> .`
```
so turtle function needs to parse content in synchronous way.

**Comment by RubenVerborgh** [comment]
This is indeed not supported currently:
```JavaScript
var parser = N3.Parser();
parser.parse('<http://example.com/A> a <http://example.com/B>.',
             function (error, triple, prefixes) {
               if (!triple)
                 console.log('Parsing done')
             });
console.log('Next statement');
```
gives
```
Next statement
Parsing done
```

That's not what you want. The reason for this is that I wanted compatible behavior with the case where the input is streaming.

However, I think you bring a very relevant use case to the table, and I might need to reconsider my initial design decision. That would be a breaking change in the API, but we have a pending breaking change anyway, so we could release this as `0.5.x`.

Let me investigate this.

**Comment by RubenVerborgh** [comment]
Parsing is now synchronous if no callback is passed, enabling support for your use case.
