### ISSUE TITLE
Parallel N3 parsing with parser as singleton can result in input 'null' in N3 lexer, exception

### ISSUE THREAD

**Issue by wallacethefmh** [RubenVerborgh/N3.js#62]
I am parsing large N3 files in parallel. I've noticed that sometimes when two files are being parsed in parallel or close to at the same time, I will get the following unhandled error:

```/devhomes/wboyd/atk-proxy/node_modules/n3/lib/N3Lexer.js:98
          firstChar = input[0], match = null, matchLength = 0, unescaped, inco
                           ^
TypeError: Cannot read property '0' of null
    at Object.N3Lexer._tokenizeToEnd (/devhomes/wboyd/atk-proxy/node_modules/n3/lib/N3Lexer.js:98:28)
    at Immediate._onImmediate (/devhomes/wboyd/atk-proxy/node_modules/n3/lib/N3Lexer.js:331:38)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```
I believe this happens because this._input inside the N3Lexer can change to null after parsing. I think this is only happening because I am using the N3Parser as a singleton instead of creating an N3Parser for each parsing job. I am not sure if this is a bug, since the workaround is just to create an instance of the N3Parser for each parsing job, which is fine for my case, but I figured I would report it.

**Comment by wallacethefmh** [comment]
And just to follow up, I think that changing

https://github.com/RubenVerborgh/N3.js/blob/master/lib/N3Lexer.js#L318
to
`self._tokenizeToEnd(callback, true);`

Could fix this issue, but that might not be what you want. Another option could be to bind the input string as a variable to pass into _tokenizeToEnd

**Comment by RubenVerborgh** [comment]
Thanks for reporting, @wallacethefmh, better to be safe than sorry.

However, an `N3Parser` instance is a stateful object; and that state is tied to the stream you are currently parsing. Much worse things can go wrong then just the `null` exception: subjects of stream 1 could appear in the output of stream 2 and vice-versa.

In other words: each new document requires a new `N3Parser` instance, so this is not a bug.

If you think it is necessary to clarify this in the documentation, please let me know.

**Comment by wallacethefmh** [comment]
Sounds good, I have not run into this with other parsing libraries, but also haven't replicated these circumstances, so I am not sure if it needs to be documented. Thanks for taking a look 👍
