### ISSUE TITLE
Encoded SPARQL query URI does not parse

### ISSUE THREAD

**Issue by ktk** [RubenVerborgh/N3.js#63]
The following Turtle does not parse with N3.js:

```turtle
@prefix rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix ns1:	<https://gont.ch/> .
<http://classifications.data.admin.ch/municipality/1>	rdf:type	ns1:PoliticalMunicipality ,
		ns1:Municipality .
@prefix owl:	<http://www.w3.org/2002/07/owl#> .
@prefix dbpedia:	<http://dbpedia.org/resource/> .
<http://classifications.data.admin.ch/municipality/1>	owl:sameAs	dbpedia:Aeugst_am_Albis .
@prefix ns4:	<http://purl.org/dc/terms/> .
<http://classifications.data.admin.ch/municipality/1>	ns4:identifier	1 ;
	ns1:id	1 ;
	ns1:municipalityVersion	<http://classifications.data.admin.ch/municipalityversion/11348> ,
		<http://classifications.data.admin.ch/municipalityversion/13256> ;
	ns1:poulationStatistics	<http://lindas-data.ch/sparql?default-graph-uri=&query=PREFIX+gont%3A+\u003Chttps%3A%2F%2Fgont.ch%2F\u003E%0D%0A%0D%0ACONSTRUCT+{%0D%0A++\u003Chttp%3A%2F%2Fclassifications.data.admin.ch%2Fmunicipality%2F1\u003E+gont%3ApopulationSegment+[%0D%0A++++gont%3AfromAge+%3FfromAge+%3B%0D%0A++++gont%3AtoAge+%3FtoAge+%3B%0D%0A++++gont%3AmalePopulation+%3FMale_Inhabitants+%3B%0D%0A++++gont%3AfemalePopulation+%3FFemale_Inhabitants+%0D%0A++]%0D%0A}%0D%0A%0D%0AWHERE%0D%0A{%0D%0A++{%0D%0A++++SELECT+%0D%0A++++++(%3Fageinterval+AS+%3FfromAge)%0D%0A++++++(%3Fageinterval%2B4+AS+%3FtoAge)%0D%0A++++++(SUM(IF(%3Fsex%3D\u003Chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fcode%2F1.0%2FCL_SEX%2F2\u003E%2C%3Fnumber%2C0))+AS+%3FFemale_Inhabitants)%0D%0A++++++(SUM(IF(%3Fsex%3D\u003Chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fcode%2F1.0%2FCL_SEX%2F1\u003E%2C%3Fnumber%2C0))+AS+%3FMale_Inhabitants)%0D%0A++++WHERE%0D%0A++++{%0D%0A++++++++%3Fs+\u003Chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fproperty%2FNB_PERSON\u003E+%3Fnumber%3B%0D%0A++++++++\u003Chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fproperty%2FPOPULATIONTYPE\u003E+%3Fptype%3B%0D%0A++++++++\u003Chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fproperty%2FSEX\u003E+%3Fsex%3B%0D%0A++++++++\u003Chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fproperty%2FREPORTINGMUNICIPALITYID\u003E+%3Fremuniuri%3B%0D%0A++++++++\u003Chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fproperty%2FAGE\u003E+%3Fage.%0D%0A%0D%0A++++++++%3Fremuniuri+\u003Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23notation\u003E+\u00221\u0022.%0D%0A++++++++%3Fage+\u003Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23notation\u003E+%3Fagenumber.%0D%0A%0D%0A++++++++%3Fptype+\u003Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23notation\u003E+%3Fpnumber.%0D%0A++++++++FILTER+((xsd%3Aint(%3Fpnumber))+\u003C%3D+2)%0D%0A%0D%0A++++++}%0D%0A++++++GROUP+BY+((FLOOR((xsd%3Aint(%3Fagenumber))%2F5)*5)+AS+%3Fageinterval)%0D%0A++++++ORDER+BY+DESC(xsd%3Aint(%3Fageinterval))%0D%0A++}%0D%0A}> .
```

The file is served from Virtuoso, you can get it by requesting `text/turtle` from http://classifications.data.admin.ch/municipality/1

Is Virtuoso delivering wrong Turtle here or is it a N3.js bug?

**Comment by RubenVerborgh** [comment]
My first guess would be a Virtuoso Turtle bug. [This has happened before.](https://github.com/LinkedDataFragments/Server.js/blob/v2.0.2/lib/datasources/SparqlDatasource.js#L43-L51) I'll investigate.

**Comment by RubenVerborgh** [comment]
`\u003` is an invalid IRI character. Hence, N3.js needs to reject the document to remain compatible with the Turtle spec.

**Comment by ktk** [comment]
Ok thanks,  FYI `rapper` from Redland doesn't parse it either, bails out with a `syntax error at '<'`.

**Comment by retog** [comment]
The \u sequence comes from escaping characters in the URI that are invalid in turtle. How to escape them correctly? (Using % would make it a different URI for RDF)

**Comment by RubenVerborgh** [comment]
@retog `\u` sequences are fine, as long as they resolve to characters that are valid in IRIs.
It _has_ to be a different IRI, because the current IRI is an invalid one, so any equivalent notation would lead to an invalid IRI. The only way is, as you suggest, to use an `%` escape sequence, resulting in a different, but valid, IRI.

**Comment by retog** [comment]
RFC 3987 says: 

> Systems accepting IRIs MAY also deal with the printable characters in
   US-ASCII that are not allowed in URIs, namely "<", ">", '"', space,
   "{", "}", "|", "\", "^", and "`"

From this and the IRI grammar rules I would have concluded that these signs are legal in IRIs.

**Comment by RubenVerborgh** [comment]
Well, RFC3987 says that systems _MAY_ accept them, so they are only legal for some systems.

Given Postel's law, the safe assumption is thus to not have them in a system, so any IRIs that come out of it will be accepted by other systems. So in that sense, Turtle made the right choice. Also, accepting `{` but not `<` would be strange, and `{` is used in the context of IRI templates.
