### ISSUE TITLE
Parser fails on long IRIs

### ISSUE THREAD

**Issue by retog** [RubenVerborgh/N3.js#64]
Even when creating IRIs that do not require escaping characters with the \u-notation (which doesn't work as described in Issue #63), the parser has issues with long IRIs, like `<http://lindas-data.ch/sparql?default-graph-uri=&query=PREFIX+gont%3A+%3chttps%3A%2F%2Fgont.ch%2F%3e%0D%0A%0D%0ACONSTRUCT+{%0D%0A++%3chttp%3A%2F%2Fclassifications.data.admin.ch%2Fmunicipality%2F1%3e+gont%3ApopulationSegment+[%0D%0A++++gont%3AfromAge+%3FfromAge+%3B%0D%0A++++gont%3AtoAge+%3FtoAge+%3B%0D%0A++++gont%3AmalePopulation+%3FMale_Inhabitants+%3B%0D%0A++++gont%3AfemalePopulation+%3FFemale_Inhabitants+%0D%0A++]%0D%0A}%0D%0A%0D%0AWHERE%0D%0A{%0D%0A++{%0D%0A++++SELECT+%0D%0A++++++(%3Fageinterval+AS+%3FfromAge)%0D%0A++++++(%3Fageinterval%2B4+AS+%3FtoAge)%0D%0A++++++(SUM(IF(%3Fsex%3D%3chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fcode%2F1.0%2FCL_SEX%2F2%3e%2C%3Fnumber%2C0))+AS+%3FFemale_Inhabitants)%0D%0A++++++(SUM(IF(%3Fsex%3D%3chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fcode%2F1.0%2FCL_SEX%2F1%3e%2C%3Fnumber%2C0))+AS+%3FMale_Inhabitants)%0D%0A++++WHERE%0D%0A++++{%0D%0A++++++++%3Fs+%3chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fproperty%2FNB_PERSON%3e+%3Fnumber%3B%0D%0A++++++++%3chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fproperty%2FPOPULATIONTYPE%3e+%3Fptype%3B%0D%0A++++++++%3chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fproperty%2FSEX%3e+%3Fsex%3B%0D%0A++++++++%3chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fproperty%2FREPORTINGMUNICIPALITYID%3e+%3Fremuniuri%3B%0D%0A++++++++%3chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fproperty%2FAGE%3e+%3Fage.%0D%0A%0D%0A++++++++%3Fremuniuri+%3chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23notation%3e+%221%22.%0D%0A++++++++%3Fage+%3chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23notation%3e+%3Fagenumber.%0D%0A%0D%0A++++++++%3Fptype+%3chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23notation%3e+%3Fpnumber.%0D%0A++++++++FILTER+((xsd%3Aint(%3Fpnumber))+%3c%3D+2)%0D%0A%0D%0A++++++}%0D%0A++++++GROUP+BY+((FLOOR((xsd%3Aint(%3Fagenumber))%2F5)*5)+AS+%3Fageinterval)%0D%0A++++++ORDER+BY+DESC(xsd%3Aint(%3Fageinterval))%0D%0A++}%0D%0A}>`, the error message is:
```Error: Syntax error: unexpected "<http://lindas-data.ch/sparql?default-graph-uri=&query=PREFIX+gont%3A+%3chttps%3A%2F%2Fgont.ch%2F%3e%0D%0A%0D%0ACONSTRUCT+{%0D%0A++%3chttp%3A%2F%2Fclassifications.data.admin.ch%2Fmunicipality%2F1%3e+gont%3ApopulationSegment+[%0D%0A++++gont%3AfromAge+%3FfromAge+%3B%0D%0A++++gont%3AtoAge+%3FtoAge+%3B%0D%0A++++gont%3AmalePopulation+%3FMale_Inhabitants+%3B%0D%0A++++gont%3AfemalePopulation+%3FFemale_Inhabitants+%0D%0A++]%0D%0A}%0D%0A%0D%0AWHERE%0D%0A{%0D%0A++{%0D%0A++++SELECT+%0D%0A++++++(%3Fageinterval+AS+%3FfromAge)%0D%0A++++++(%3Fageinterval%2B4+AS+%3FtoAge)%0D%0A++++++(SUM(IF(%3Fsex%3D%3chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fcode%2F1.0%2FCL_SEX%2F2%3e%2C%3Fnumber%2C0))+AS+%3FFemale_Inhabitants)%0D%0A++++++(SUM(IF(%3Fsex%3D%3chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fcode%2F1.0%2FCL_SEX%2F1%3e%2C%3Fnumber%2C0))+AS+%3FMale_Inhabitants)%0D%0A++++WHERE%0D%0A++++{%0D%0A++++++++%3Fs+%3chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fproperty%2FNB_PERSON%3e+%3Fnumber%3B%0D%0A++++++++%3chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fproperty%2FPOPULATIONTYPE%3e+%3Fptype%3B%0D%0A++++++++%3chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fproperty%2FSEX%3e+%3Fsex%3B%0D%0A++++++++%3chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fproperty%2FREPORTINGMUNICIPALITYID%3e+%3Fremuniuri%3B%0D%0A++++++++%3chttp%3A%2F%2Fdata.admin.ch%2Fbfs%2Fproperty%2FAGE%3e+%3Fage.%0D%0A%0D%0A++++++++%3Fremuniuri+%3chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23notation%3e+%221%22.%0D%0A++++++++%3Fage+%3chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23notation%3e+%3Fagenumber.%0D%0A%0D%0A++++++++%3Fptype+%3chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23notation%3e+%3Fpnumber.%0D%0A++++++++FILTER+((xsd%3Aint(%3Fpnumber))+%3c%3D+2)%0D%0A%0D%0A++++++}%0D%0A++++++GROUP+BY+((FLOOR((xsd%3Aint(%3Fagenumber))%2F5)*5)+AS+%3Fageinterval)%0D%0A++++++ORDER+BY+DESC(xsd%3Aint(%3Fageinterval))%0D%0A++}%0D%0A}>" on line ...```

**Comment by RubenVerborgh** [comment]
The `\u` notation is supported and not a problem in itself. It's only a problem if the notation (`\u` or otherwise) results in an invalid IRI character. The IRIs above contain invalid characters: [`{` and `}` are not allowed in IRIs](https://www.w3.org/TR/turtle/#grammar-production-IRIREF), so `N3.js` must reject the input to remain spec-compatible.

**Comment by RubenVerborgh** [comment]
Replacing `{` by `%7B` and `}` by `%7D` makes your IRI valid, so N3.js will parse it.

**Comment by retog** [comment]
Interestingly the IRI works in RDF/XML that results as valid by the W3C validator, so either the W3C validator is wrong or not all valid RDF can be serialized as turtle.

But using %7B and %7D should work for the practical purpose at hand, thanks @RubenVerborgh .

Closing the issue, as it seems that is something is broken, it's the turtle spec.

**Comment by RubenVerborgh** [comment]
> so either the W3C validator is wrong or not all valid RDF can be serialized as turtle.

This seems something very relevant to discuss on the mailing lists. I'm really hoping is just the validator.
