### ISSUE TITLE
Can't parse large Turtle strings in Safari

### ISSUE THREAD

**Issue by adolski** [RubenVerborgh/N3.js#66]
Hi, I'm using N3 in the browser with 4.2MB of Turtle data:

    $.get(rdfUrl, function(data) {
        var parser = N3.Parser();
        parser.parse(data, function(error, triple, prefixes) {
            ...
        });
    });

This code works great in Firefox and Chrome, but current versions of Safari (Mac and iOS) absolutely die on it (warning: memory use spirals out of control and you have to close the tab immediately).

Performance seems to degrade logarithmically -- if I give `parse()` only 100KB or so of text, it can handle it. 200KB is noticeably slower. 500KB kills it.

**Comment by RubenVerborgh** [comment]
Mmm, that points in the direction of a Safari bug. I'll try to see what I can do; any clues are welcome.

**Comment by RubenVerborgh** [comment]
A console profile revealed that the root cause of this is Safari's slow regular expression performance. There's unfortunately nothing I can really do about this, as parsers rely heavily on them.

Here's the code used for testing:
```
<html>
  <script src="browser/n3-browser.js"></script>
  <script>
    var size = 100 * 1024, turtle = '';
    while (turtle.length < size)
      turtle += '<a> <b> <c>.\n';
    var parser = new N3.Parser();
    console.profile();
    parser.parse(turtle, function (error, triple) {
      if (error)
        console.error(error);
      else if (!triple) {
        console.profileEnd();
        console.log('done');
      }
    });
  </script>
</html>
```
