### ISSUE TITLE
N3Util.createLiteral does not escape correctly

### ISSUE THREAD

**Issue by leipert** [RubenVerborgh/N3.js#67]
Hey there.

```js
// returns """, whereas it should return "\""
N3Util.createLiteral('"')
```

Should I write a PR to fix this or do you want to this yourself?

**Comment by RubenVerborgh** [comment]
Hi @leipert,

Note that `N3Util` creates literals in the [N3.js representation](https://github.com/RubenVerborgh/N3.js#triple-representation) ([details](https://github.com/RubenVerborgh/N3.js#utility)), which is _not_ Turtle.

The N3.js representation of a (typeless and languageless) literal is the value of that literal surrounded by double quotes, without escaping.

If you want to obtain a Turtle representation, `N3.Writer` is the way to go. You'll see it correctly escapes literals in Turtle syntax.

Cheers,

Ruben

**Comment by leipert** [comment]
Okay. thank you, maybe it should be added to the documentation, that they are not real rdf literals and do not properly escape.

Thank you anyway 👍

**Comment by RubenVerborgh** [comment]
Yes, I linked to the [relevant part in the documentation](https://github.com/RubenVerborgh/N3.js#utility) above:

> Note the difference between 'http://example.org/' (IRI) and '"http://example.org/"' (literal). 
> Also note that the double quoted literals are not raw Turtle/TriG syntax:

>     N3Util.isLiteral('"This word is "quoted"!"'); // true
>     N3Util.isLiteral('"3"^^http://www.w3.org/2001/XMLSchema#integer'); // true

**Comment by leipert** [comment]
Sorry 😰 
Thank you for quick responses and hints.

**Comment by RubenVerborgh** [comment]
No worries, rather an issue too many than one too few :wink:
