### ISSUE TITLE
inverse index in N3Store not updated when adding blank nodes

### ISSUE THREAD

**Issue by florianthalmann** [RubenVerborgh/N3.js#68]
Hey @RubenVerborgh is it a deliberate decision in `N3Store.createBlankNode` not to update the inverse index (`this._entities`)? When I query the store with one variable, e.g. `store.find(subject, predicate, null)`, blank node objects end up being undefined in the result. Should I create a pull request? I simply added the following line to the end of the function:
```javascript
// Add the blank node to the entities, avoiding the generation of duplicates
this._ids[name] = ++this._id;
this._entities[this._id] = name; //<-------
return name;
```
Thanks!

**Comment by RubenVerborgh** [comment]
Hi @florianthalmann, thanks for reporting. Not intentional at all! PR welcome if you have a test. (If not, I can do it.)

**Comment by florianthalmann** [comment]
Just added some tests and made a pull request. Thanks!

**Comment by RubenVerborgh** [comment]
Following up in #69.
