### ISSUE TITLE
URIs fragments in Turtle

### ISSUE THREAD

**Issue by StatelessCat** [RubenVerborgh/N3.js#70]
Hey,
I was loading the turtle-serialised PROV-O ontology into N3.JS, and I realized N3.JS does not accept URIs with fragments. 
For example: `@base <http://www.w3.org/ns/prov-dc#> .` causes an `Error: Invalid base IRI` .

I think the Turtle spec considers URI as RFC3986, but maybe I'm missing something.

Here you will find a minimal working example: https://github.com/StatelessCat/mwe-n3js/blob/master/mwe-n3.js .
I also notice a bug on triple patterns with `<#>` as subject, but I think this is a direct consequence of the previous issue.

Thanks in advance for your help.
Raphaël .

**Comment by RubenVerborgh** [comment]
Interesting. I followed `cwm` and `eye` here, but I don't immediately find a reference in the spec indeed. Let me investigate.

**Comment by RubenVerborgh** [comment]
Thanks for reporting, this should be fixed now.

I also added a [test with `<#>` as subject](https://github.com/RubenVerborgh/N3.js/commit/3ba2ffa7c415e243aab18fa87986fe2fe7d61b17#diff-f812d6f60dce3c6e90a6296314a3d3f2R435) and this seems to work as expected. Any counterexamples?

**Comment by StatelessCat** [comment]
Thanks for the fix (:, I don't see any counterexample.
