### ISSUE TITLE
Construct TypeScript Definitions

### ISSUE THREAD

**Issue by phreed** [RubenVerborgh/N3.js#71]
I have been working on a set of [typescript](http://www.typescriptlang.org/) [definitions](http://www.typescriptlang.org/docs/handbook/writing-declaration-files.html) for N3.
I am planning on including them in [DefinitelyTyped](http://definitelytyped.org/) but I would prefer to include them in [this package](https://github.com/RubenVerborgh/N3.js/issues/new).

Should I fork, update and make a pull request?

**Comment by phreed** [comment]
Made a pull request #72

**Comment by phreed** [comment]
I have added a set of typings to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11997).
There are a couple of things to take care of.
- extending other libraries with `pipe()` functions.
- creating constructors for `Parser` and `Writer` classes.

**Comment by RubenVerborgh** [comment]
I'm not a TypeScript user, but it looks good to me. Thanks for your efforts!
