### ISSUE TITLE
Newest keyword support introduces a regression

### ISSUE THREAD

**Issue by leipert** [RubenVerborgh/N3.js#75]
Turtle does not allow for case insensitive @keywords `@prefix` and `@base`.
See (Note 1) in grammar section in turtle spec: 
https://www.w3.org/TR/turtle/#sec-grammar-grammar

But since 7ca92933d4eefeaecdc18f20aeea7732e271045f the keyword regex matches case insensitive: [N3Lexer.js#L58](https://github.com/RubenVerborgh/N3.js/blob/7ca92933d4eefeaecdc18f20aeea7732e271045f/lib/N3Lexer.js#L58)

**Comment by RubenVerborgh** [comment]
Not a bug, since the parser matches them in a case-sensitive way; added a test to ensure this behavior.

**Comment by leipert** [comment]
Okay. Thanks, your like the fastest responder on every issue 👍

**Comment by RubenVerborgh** [comment]
Trying hard, but the truth is that I happen to be working on N3.js tonight :wink:
