### ISSUE TITLE
Add comment token to N3Lexer

### ISSUE THREAD

**Issue by leipert** [RubenVerborgh/N3.js#76]
I am using the N3.Lexer to write a turtle formatter (Mainly adding prefixes to the turtle). For me it would really make sense to be able to have access to the original comments, so that i can place them where they belong.

This should not slow the parser down too much.

Should I help you with the implementation?

**Comment by RubenVerborgh** [comment]
Interesting use case; you're probably one of the few people using the lexer directly.

At the moment, comments are parsed away along with newlines. Are you also interested in the whitespace/newlines, or just the comments?

I could enable your use case with a flag (but won't do it by default, so the parser doesn't receive unnecessary tokens).

**Comment by leipert** [comment]
I am actually just interested in the comments. And a flag would be good enough.

Before I started using the Lexer directly, I just used N3.Parser And N3.Writer to parse a turtle file and print it nicely with prefixes that we wanted. But now we needed blank-node support where the above solution is not a good fit (as it serializes the blank nodes).

So basically I iterate over the turtle with help of the lexer and replace IRIs with prefixes, indent lines the right way, etc.

Once the project is in a nice place, I will send you an issue here and we could talk about merging the two 👍

**Comment by RubenVerborgh** [comment]
> I am actually just interested in the comments. And a flag would be good enough.

Alright, I'll implement this behind a flag.

> But now we needed blank-node support where the above solution is not a good fit (as it serializes the blank nodes).

Indeed; there's no way to do this nicely on a stream, and N3.js is a streaming library.
