### ISSUE TITLE
Automatic anonymous blank nodes

### ISSUE THREAD

**Issue by pheyvaer** [RubenVerborgh/N3.js#77]
Is it possible to set a property of the `writer` to automatically write all blank nodes as anonymous blank nodes? Anonymous blank nodes are supported in #41. However, that means that you need to check yourself when you need to add it as a anonymous blank node to the writer.

**Comment by RubenVerborgh** [comment]
Hi @pheyvaer, on streaming data, it is impossible to write blank nodes as anonymous nodes in general. Consider the following example:

- `_:b1 <p1> <o1>`
- `_:b2 <p2> <o2>`
- `_:b1 <p3> <o3>`

The writer is streaming: it needs to make a decision after every triple. So you would get:

- `[] <p1> <o1>.`
- `[] <p2> <o2>.`
- _problem_

The thirds triple cannot be attached to the first blank node anymore.

So the only way to write anonymous blank nodes is `writer.addTriple(writer.blank(), 'p', 'o1);`. If you have prior knowledge about the data (such as that it is sorted by subject), you might create a superclass of writer that writes them anonymously.
