### ISSUE TITLE
How does the "graph" key work?

### ISSUE THREAD

**Issue by dherault** [RubenVerborgh/N3.js#79]
Hi,

I'm parsing some Turtle file using the following code:

```javascript
const parser = require('n3').Parser();
console.log(parser.parse(data));
```
I get an array with the following item shape `{ subject, object, predicate, graph }` but `graph` is always an empty string. Can I populate it automatically using `parse()`, from my ontology namespace for example ?

**Comment by RubenVerborgh** [comment]
Graph is the “fourth component” introduced in RDF 1.1. Turtle does not support graphs, so the graph will always be empty, as you observed. However, if you parse N-Quads or TriG, then the graph will be stored in the `graph` attribute.

So the only way to populate `graph`, is to feed a document with graphs into the parser.

**Comment by dherault** [comment]
Thank you for both that and the lib
