### ISSUE TITLE
the prefix 'prefix' incorrectly throws an error

### ISSUE THREAD

**Issue by smurp** [RubenVerborgh/N3.js#80]
The file `http://prefix.cc/popular/all.ttl` amusingly contains the line:

    @prefix prefix:     <http://prefix.cc/>.

which causes N3.js's parser to emit:
  
    Error: Expected prefix to follow @prefix on line 1.

As far as I can tell the spec says nothing about `prefix` being a reserved term which can not be used as a prefix itself.  Admittedly it is unexpected though!

**Comment by RubenVerborgh** [comment]
This is genuinely funny 😄  It errors because it expects prefix to follow @prefix, and fails because prefix follows @prefix.

**Comment by RubenVerborgh** [comment]
Fixed in a82c435cbcd7f4ebe4b21ccbefe70bbe19a1d9ab, released as v0.8.3.
