### ISSUE TITLE
@base is not emitted by N3Parser

### ISSUE THREAD

**Issue by smurp** [RubenVerborgh/N3.js#81]
`@base` is correctly digested by N3Parser and the triples 'based' on it are correctly expanded but the parser does not communicate anything about whether there **was** a base in its output as, for example, the `@prefix` lines are communicated.

A possible way to support backward-compatibly communicating this information would be to have the callback method that N3Parser.parse expects to receive an additional fourth `base` argument.

0. err
0. triple
0. prefixes
0. base

To make it backwardly-compatible the base argument could be conveyed in the same call as the prefixes are.  Perhaps there would be a need for an option to the N3Parser constructor to force a call in the event that there is a `@base` but there are no `@prefix` lines.

**Comment by RubenVerborgh** [comment]
It's right, base is not emitted. What would be use cases for knowing this base? I'm just not sure it's very relevant.

Also, note that there might be multiple bases in a document. Which one(s) would you need and why?

**Comment by RubenVerborgh** [comment]
Closing this for now because input is needed to resolve it. Feel free to reopen.
