### ISSUE TITLE
N3Lexer comments option causes N3Parser Error

### ISSUE THREAD

**Issue by smurp** [RubenVerborgh/N3.js#82]
N3Lexer with the comments option engaged and when a comment is then encountered causes N3Parser to raises

    Error: Expected entity but got comment on line 1.

This begs the question *But what SHOULD be done with comments?*. :-)

I will leave that to another issue (or maybe a pull request if you would prefer I beat you to handling this one).

BTW: Thanks for this absolutely beautiful piece of code!

**Comment by RubenVerborgh** [comment]
Comments should be ignored 😄  I don't see a use for them in the parser.
They were added for #76, in case somebody wants to write a parser that does something with comments.

Do you have a suggestion for what the parser could do with them?

**Comment by RubenVerborgh** [comment]
Closing this for now because input is needed to resolve it. Feel free to reopen.
