### ISSUE TITLE
Valid 'blankNodePropertyList' followed by '.' causes N3Parser error

### ISSUE THREAD

**Issue by jimsmart** [RubenVerborgh/N3.js#84]
Hi,

I am encountering an error when parsing some Turtle/N3 using N3Parser.

Repro:

```javascript
var N3 = require('n3');
var parser = N3.Parser();

var turtle = `
@prefix gr: <http://purl.org/goodrelations/v1#> .

[ a           gr:Offering ;
  gr:category "42"
] .

`;

parser.parse(turtle,
             function (error, triple, prefixes) {
               if (error) throw error;
    
               if (!triple)
                 console.log("That's all, folks!")
             });
```

Output:
Error: Unexpected . on line 6.

Expected output:
That's all, folks!

The relevant Turtle spec:
```
[1]	turtleDoc	::=	statement*
[2]	statement	::=	directive | triples '.'
[6]	triples	::=	subject predicateObjectList | blankNodePropertyList predicateObjectList?
[14]	blankNodePropertyList	::=	'[' predicateObjectList ']'
```

**Comment by jimsmart** [comment]
In the real-world, similar productions appear in the downloadable N3 for both the gr and pro vocabularies:
http://lov.okfn.org/dataset/lov/vocabs/prov
http://lov.okfn.org/dataset/lov/vocabs/gr
(The download link is the n3-logo, on the right-hand-side of the page)

**Comment by RubenVerborgh** [comment]
Interesting, thought I had a test case for this. Will check!

**Comment by jimsmart** [comment]
I don't see one? But I came up with this, if it helps at all? 

```
    it('should parse statements with a blank node and no trailing predicate-object list',
      shouldParse('[<a> <b>].',
                  ['_:b0', 'a', 'b']));
```
(I don't have a fix to go with it though, sorry!)

**Comment by jimsmart** [comment]
Thanks
