### ISSUE TITLE
N3Store - extend API?

### ISSUE THREAD

**Issue by jimsmart** [RubenVerborgh/N3.js#86]
Hi (and seasonal greets),

I have some extensions to the N3Store API - would you be interested in reviewing them for possible inclusion?

Additional finders:-

findGraphs(subject, predicate, object)
findGraphsByIRI(subject, predicate, object)
findSubjects(predicate, object, graph)
findSubjectsByIRI(predicate, object, graph)
findPredicates(subject, object, graph)
findPredicatesByIRI(subject, object, graph)
findObjects(subject, predicate, graph)
findObjectByIRI(subject, predicate, graph)

Currently, with only finders for quads, if one wants to get graphs/subject/predicates/objects one has to query out all the related quads and then process them down, which is a waste of CPU when N3Store has perfectly good indexes to use :)

Iterators:-

forEach(fn, subject, predicate, object, graph)
forEachByIRI(fn, subject, predicate, object, graph)
some(fn, subject, predicate, object, graph)
someByIRI(fn, subject, predicate, object, graph)
every(fn, subject, predicate, object, graph)
everyByIRI(fn, subject, predicate, object, graph)
forGraphs(fn, subject, predicate, object)
forGraphsByIRI(fn, subject, predicate, object)
forSubjects(fn, predicate, object, graph)
forSubjectsByIRI(fn, predicate, object, graph)
forPredicates(fn, subject, object, graph)
forPredicatesByIRI(fn, subject, object, graph)
forObjects(fn, subject, predicate, graph)
forObjectByIRI(fn, subject, predicate, graph)

Having iterators means one can work with data in the store without any intermediary allocations for results.

Sadly I've not written a test suite for the above, but I am using all of them successfully in a couple of projects I am working on (both in the browser and with Node). (FWIW. these methods are rough ports of some Go code I've written, but I've not yet got round to porting the tests). 

Earlier today, I started splitting some of these functions into separate branches (smaller pull requests are always better), but unfortunately - due to how I've implemented them - they're a bit interdependent on one another, so that didn't quite work out.

I do realise the lack of tests makes the whole proposition less appealing to you, but I thought I'd get the ball rolling by opening discussion anyhow :)

Happy to submit as a pull request or as an attachment to this issue.

**Comment by jimsmart** [comment]
[N3Store.js.zip](https://github.com/RubenVerborgh/N3.js/files/677768/N3Store.js.zip)

^^ Attached, to save some back and forth

**Comment by jimsmart** [comment]
Pull request #87

**Comment by RubenVerborgh** [comment]
Great, let's follow up in #87!
