### ISSUE TITLE
Question re: licensing/copyright attribution

### ISSUE THREAD

**Issue by jimsmart** [RubenVerborgh/N3.js#88]
In other news, I've recently opened a repo which has some code that draws heavily from the code of N3Store.

https://github.com/jimsmart/store4
(It's a rehash/rewrite of a graph implementation that I have been using for some time)

Could you please confirm that my attribution to your project is sufficient? (see end of readme - and same attribution within the docs). 

I realise that there's no actual code re-use, and that using maps for indexes already has 'prior art', but I figured I should give credit where credit is due :)

**Comment by RubenVerborgh** [comment]
That's perfect, thanks so much for asking!
