### ISSUE TITLE
N3Writer: Prefixes are not applied for URIs with special characters

### ISSUE THREAD

**Issue by mzabel** [RubenVerborgh/N3.js#92]
The replacement of URI fragments by prefixes during RDF writing is only applied if the URI does not contain certain special characters.

The following code

```
var writer = N3.Writer();
writer.addPrefix('dbr', 'http://dbpedia.org/resource/');
writer.addTriple('http://dbpedia.org/resource/The_Wall',
                 'http://purl.org/dc/terms/subject',
                 'http://dbpedia.org/resource/Category:Concept_albums');
writer.addTriple('http://dbpedia.org/resource/50_Words_for_Snow',
                'http://purl.org/dc/terms/subject',
                'http://dbpedia.org/resource/Category:Concept_albums');
writer.addTriple('http://dbpedia.org/resource/Pictures_at_an_Exhibition_(Emerson,_Lake_&_Palmer_album)',
                 'http://purl.org/dc/terms/subject',
                 'http://dbpedia.org/resource/Category:Concept_albums');

writer.end(function (error, result) { console.log(result); });
```

gives the following output:

```
@prefix dbr: <http://dbpedia.org/resource/>.

dbr:The_Wall <http://purl.org/dc/terms/subject> <http://dbpedia.org/resource/Category:Concept_albums>.
<http://dbpedia.org/resource/50_Words_for_Snow> <http://purl.org/dc/terms/subject> <http://dbpedia.org/resource/Category:Concept_albums>.
<http://dbpedia.org/resource/Pictures_at_an_Exhibition_(Emerson,_Lake_&_Palmer_album)> <http://purl.org/dc/terms/subject> <http://dbpedia.org/resource/Category:Concept_albums>.
```

However, I would expect the prefix to be applied to all three dbpedia resource URIs.

The problem seems to be the Regex used for the prefix replacement. Is it intended to be that restrictive?

https://github.com/RubenVerborgh/N3.js/blob/a191cd25948900b3f8eba53360a3ef851394495e/lib/N3Writer.js#L225

**Comment by RubenVerborgh** [comment]
Thanks for asking this.

Yes, it is intended to be that restrictive, for performance reasons. The current implementation focuses on “easy to find and apply” prefixes that don't require complex matching nor escaping. As a result, the output is always valid Turtle/TriG (which is crucial), but might be longer than the strictly needed minimum length. However, gzipping or another compression format would remove that difference (and in my experience, gzipped N-Triples parses faster than Turtle).

**Comment by mzabel** [comment]
Okay. Thank you for the explanation!
