### ISSUE TITLE
Add option to silence @prefix definition writing

### ISSUE THREAD

**Issue by nichtich** [RubenVerborgh/N3.js#96]
Add an option to skip writing `@prefix` definitions in [N3Writer.js line 214](https://github.com/RubenVerborgh/N3.js/blob/a191cd25948900b3f8eba53360a3ef851394495e/lib/N3Writer.js#L214), e.g.

~~~js
N3.Writer({ prefixes: { ... }, writePrefixes: false })
~~~

This is useful if `@prefix` definitions have already been written by other means or if they are not required for other reasons (e.g. Turtle snippets for human consumption).

**Comment by RubenVerborgh** [comment]
I'm hesitant to do this, as this would make N3Writer output invalid Turtle documents.

I'd propose instead to use the Node.js stream mechanism and pipe this through a stream that deletes lines starting with `@prefix`. Would that work for you?
