### ISSUE TITLE
What would be a best practice to use a white list for triples

### ISSUE THREAD

**Issue by hydrarulz** [RubenVerborgh/N3.js#98]
Currently I'm loading a Turtle formatted RDF and I have a white list of **rdf:type**'s.

How would you suggest using n3 to output a different Turtle formatted RDF containing only the **rdf:type**'s in the white list?

I'm looking at your `N3Writer` and `N3Parser` but don't know if it's even possible doing this

**Comment by RubenVerborgh** [comment]
What I would do is use the `N3StreamWriter` (so the `Stream` variant) and them implement a [`Transform` stream](https://nodejs.org/api/stream.html#stream_class_stream_transform) that performs the filtering task you described.

Alternatively, you can just attach a callback to the `N3Parser` that does the filtering.

**Comment by hydrarulz** [comment]
Thanks for the quick reply. I just started playing with the callback function of `N3Parser`.

If this doesn't seem to give good results, I will try the stream approach.
