### ISSUE TITLE
N3 package does not work in node-red

### ISSUE THREAD

**Issue by fbelleau** [RubenVerborgh/N3.js#99]
I would like to use N3 in node-red project. 

First I add require('n3') in setting.js

`    //    context.global.os

    functionGlobalContext: {
        jsonld:require('jsonld'),
        n3:require('n3')
        // os:require('os'),

    },
`

then I build a flow

`[{"id":"8d6b6934.dc1f88","type":"function","z":"975d2570.62d188","name":"","func":"N3 =  global.get('n3');\n\nvar parser = N3.Parser();\nparser.parse('@prefix c: <http://example.org/cartoons#>.\\n' +\n             'c:Tom a c:Cat.\\n' +\n             'c:Jerry a c:Mouse;\\n' +\n             '        c:smarterThan c:Tom.',\n             function (error, triple, prefixes) {\n               if (triple)\n                 console.log(triple.subject, triple.predicate, triple.object, '.');\n               else\n                 console.log(\"# That's all, folks!\", prefixes)\n             });\n             \nreturn msg;","outputs":1,"noerr":0,"x":348,"y":152,"wires":[["f1d2d33b.12a55"]]}]`

then I get

`07/03/2017, 09:35:24node: 8d6b6934.dc1f88
function : (error)
"TypeError: Cannot read property 'Parser' of undefined"`

Is there incompatibility within N3 and nodered framework ? I have no problem with jsonld librairy.

**Comment by RubenVerborgh** [comment]
It seems that you load the module as `n3`, so you would either need to load it as `N3` or change the flow to `n3.Parser()`.

**Comment by fbelleau** [comment]
I have no idea why it did not work, it was not because N3 spelling. I create a firts RDF parser node the official way and it works fine.

https://github.com/fbelleau/sw4nodered/blob/master/12-n3-parser.js

problem solved.
